# Historical Fight Weighting

This notebook tests whether reducing the influence of older fights improves validation performance. The test set remains excluded from every comparison.

## 1. Initial Strategy Comparison

Compare no weighting, a hard cutoff, step weighting, and exponential decay.

In [1]:
from pathlib import Path
import sys
import pandas as pd

current = Path.cwd().resolve()
project_root = next(
    p for p in [current, *current.parents]
    if (p / "data/processed/ufcstats/fight_dataset.parquet").exists()
)
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.modeling.time_weighted_training import (
    TimeWeightConfig,
    train_time_weighted_experiment,
)
from src.modeling.ufc_modeling import (
    RandomForestConfig, CatBoostConfig, SplitConfig
)

In [2]:
rf_config = RandomForestConfig()
cat_config = CatBoostConfig()
split_config = SplitConfig()

strategies = {
    "none": TimeWeightConfig(mode="none"),
    "exclude_before_2005": TimeWeightConfig(
        mode="exclude_before", cutoff_date="2005-01-01"
    ),
    "step_before_2005_025": TimeWeightConfig(
        mode="step", cutoff_date="2005-01-01", pre_cutoff_weight=0.25
    ),
    "exponential_half_life_8": TimeWeightConfig(
        mode="exponential", half_life_years=8, minimum_weight=0.10
    ),
}

In [3]:
results = {}
for name, config in strategies.items():
    print("\n" + "=" * 80)
    print(name)
    results[name] = train_time_weighted_experiment(
        project_root=project_root,
        time_weight_config=config,
        rf_config=rf_config,
        cat_config=cat_config,
        split_config=split_config,
        evaluate_test=False,
        experiment_name=name,
    )

================================================================================
none
Temporal weighting:
  mode=none; original train=6,307; effective train=6,307; mean weight=1.0000; effective sample size=6307.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6919777	test: 0.6921598	best: 0.6921598 (0)	total: 119ms	remaining: 3m 57s
100:	learn: 0.6436785	test: 0.6693868	best: 0.6693868 (100)	total: 5.23s	remaining: 1m 38s
200:	learn: 0.6269106	test: 0.6643399	best: 0.6643151 (198)	total: 10.1s	remaining: 1m 30s
300:	learn: 0.6131275	test: 0.6635690	best: 0.6632978 (288)	total: 15s	remaining: 1m 24s
400:	learn: 0.5961288	test: 0.6627661	best: 0.6627661 (400)	total: 19.9s	remaining: 1m 19s
500:	learn: 0.5796968	test: 0.6623928	best: 0.6620925 (493)	total: 24.8s	remaining: 1m 14s
600:	learn: 0.5633403	test: 0.6636993	best: 0.6619903 (538)	total: 29.7s	remaining: 1m 9s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.66199032
bestIteration = 538

Shrink model to first 539 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.612871           0.614076 0.646797  0.662859     0.235200        0.5 305 219 172 314
validation      catboost  0.593069           0.594395 0.639753  0.661990     0.234977        0.5 293 231 180 306

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\none

================================================================================
exclude_before_2005
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,877; mean weight=1.0000; effective sample size=5877.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6912664	test: 0.6921956	best: 0.6921956 (0)	total: 39.5ms	remaining: 1m 19s
100:	learn: 0.6415821	test: 0.6679227	best: 0.6679227 (100)	total: 4.85s	remaining: 1m 31s
200:	learn: 0.6236773	test: 0.6636941	best: 0.6636941 (200)	total: 9.68s	remaining: 1m 26s
300:	learn: 0.6095764	test: 0.6619606	best: 0.6619198 (299)	total: 14.5s	remaining: 1m 21s
400:	learn: 0.5913869	test: 0.6603341	best: 0.6601097 (347)	total: 19.3s	remaining: 1m 17s
500:	learn: 0.5736798	test: 0.6603373	best: 0.6594793 (445)	total: 24.1s	remaining: 1m 12s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6594792847
bestIteration = 445

Shrink model to first 446 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest   0.60198           0.602759 0.644178  0.663330     0.235441        0.5 305 219 183 303
validation      catboost   0.59604           0.597556 0.645250  0.659479     0.233786        0.5 292 232 176 310

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2005

================================================================================
step_before_2005_025
Temporal weighting:
  mode=step; original train=6,307; effective train=6,307; mean weight=0.9489; effective sample size=6066.2
Training Random Forest...
Training CatBoost...
0:	learn: 0.6919786	test: 0.6921460	best: 0.6921460 (0)	total: 43.1ms	remaining: 1m 26s
100:	learn: 0.6434713	test: 0.6678441	best: 0.6678208 (99)	total: 4.89s	remaining: 1m 31s
200:	learn: 0.6271348	test: 0.6628165	best: 0.6628165 (200)	total: 9.74s	remaining: 1m 27s
300:	learn: 0.6118336	test: 0.6614030	best: 0.6612409 (288)	total: 14.6s	remaining: 1m 22s
400:	learn: 0.5940423	test: 0.6598722	best: 0.6595590 (395)	total: 19.4s	remaining: 1m 17s
500:	learn: 0.5766766	test: 0.6603778	best: 0.6595590 (395)	total: 24.3s	remaining: 1m 12s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6595589584
bestIteration = 395

Shrink model to first 396 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest   0.60495           0.605995 0.646393  0.662721     0.235167        0.5 303 221 178 308
validation      catboost   0.59802           0.599763 0.645937  0.659559     0.233761        0.5 290 234 172 314

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\step_before_2005_025

================================================================================
exponential_half_life_8
Temporal weighting:
  mode=exponential; original train=6,307; effective train=6,307; mean weight=0.5720; effective sample size=5423.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920451	test: 0.6921954	best: 0.6921954 (0)	total: 44.8ms	remaining: 1m 29s
100:	learn: 0.6415100	test: 0.6707290	best: 0.6707290 (100)	total: 4.97s	remaining: 1m 33s
200:	learn: 0.6206601	test: 0.6666595	best: 0.6666286 (198)	total: 9.9s	remaining: 1m 28s
300:	learn: 0.6019573	test: 0.6653417	best: 0.6652487 (236)	total: 14.8s	remaining: 1m 23s
400:	learn: 0.5829832	test: 0.6651599	best: 0.6648124 (324)	total: 19.7s	remaining: 1m 18s
500:	learn: 0.5652196	test: 0.6650273	best: 0.6644757 (453)	total: 24.6s	remaining: 1m 13s
600:	learn: 0.5481201	test: 0.6661924	best: 0.6644757 (453)	total: 29.5s	remaining: 1m 8s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6644756929
bestIteration = 453

Shrink model to first 454 iterations.

Training complete.
Selected model: random_forest
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest   0.60495           0.605622 0.641418  0.663668     0.235625        0.5 308 216 183 303
validation      catboost   0.60099           0.602775 0.635276  0.664476     0.236062        0.5 291 233 170 316

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exponential_half_life_8

In [4]:
rows = []
for strategy, result in results.items():
    for model, metrics in result["validation_metrics"].items():
        rows.append({
            "strategy": strategy,
            "model": model,
            **metrics,
            "effective_train_rows": result["weighting_summary"]["effective_train_rows"],
            "effective_sample_size": result["weighting_summary"]["effective_sample_size"],
            "mean_weight": result["weighting_summary"]["weight_mean"],
        })

comparison = pd.DataFrame(rows).sort_values(
    ["log_loss", "brier_score", "roc_auc"],
    ascending=[True, True, False],
)
comparison

,strategy,model,accuracy,balanced_accuracy,roc_auc,log_loss,brier_score,threshold,tn,fp,fn,tp,effective_train_rows,effective_sample_size,mean_weight
3,exclude_before_2005,catboost,0.596040,0.597556,0.645250,0.659479,0.233786,0.5,292,232,176,310,5877,5877.000000,1.000000
5,step_before_2005_025,catboost,0.598020,0.599763,0.645937,0.659559,0.233761,0.5,290,234,172,314,6307,6066.226038,0.948866
1,none,catboost,0.593069,0.594395,0.639753,0.661990,0.234977,0.5,293,231,180,306,6307,6307.000000,1.000000
4,step_before_2005_025,random_forest,0.604950,0.605995,0.646393,0.662721,0.235167,0.5,303,221,178,308,6307,6066.226038,0.948866
0,none,random_forest,0.612871,0.614076,0.646797,0.662859,0.235200,0.5,305,219,172,314,6307,6307.000000,1.000000
2,exclude_before_2005,random_forest,0.601980,0.602759,0.644178,0.663330,0.235441,0.5,305,219,183,303,5877,5877.000000,1.000000
6,exponential_half_life_8,random_forest,0.604950,0.605622,0.641418,0.663668,0.235625,0.5,308,216,183,303,6307,5423.037173,0.571970
7,exponential_half_life_8,catboost,0.600990,0.602775,0.635276,0.664476,0.236062,0.5,291,233,170,316,6307,5423.037173,0.571970

## 2. Broader Cutoff Search

The initial comparison suggests that a hard cutoff may help CatBoost, so more recent cutoff dates are tested before selecting a strategy.

In [5]:
rf_config = RandomForestConfig()
cat_config = CatBoostConfig()
split_config = SplitConfig()

strategies = {
    "none": TimeWeightConfig(mode="none"),
    "exclude_before_2010": TimeWeightConfig(
        mode="exclude_before", cutoff_date="2010-01-01"
    ),
    "step_before_2010_025": TimeWeightConfig(
        mode="step", cutoff_date="2010-01-01", pre_cutoff_weight=0.25
    ),
    "exponential_half_life_5": TimeWeightConfig(
        mode="exponential", half_life_years=5, minimum_weight=0.10
    ),
}

In [6]:
results = {}
for name, config in strategies.items():
    print("\n" + "=" * 80)
    print(name)
    results[name] = train_time_weighted_experiment(
        project_root=project_root,
        time_weight_config=config,
        rf_config=rf_config,
        cat_config=cat_config,
        split_config=split_config,
        evaluate_test=False,
        experiment_name=name,
    )

================================================================================
none
Temporal weighting:
  mode=none; original train=6,307; effective train=6,307; mean weight=1.0000; effective sample size=6307.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6919777	test: 0.6921598	best: 0.6921598 (0)	total: 43.3ms	remaining: 1m 26s
100:	learn: 0.6436785	test: 0.6693868	best: 0.6693868 (100)	total: 5.51s	remaining: 1m 43s
200:	learn: 0.6269106	test: 0.6643399	best: 0.6643151 (198)	total: 10.8s	remaining: 1m 36s
300:	learn: 0.6131275	test: 0.6635690	best: 0.6632978 (288)	total: 16s	remaining: 1m 30s
400:	learn: 0.5961288	test: 0.6627661	best: 0.6627661 (400)	total: 21.3s	remaining: 1m 24s
500:	learn: 0.5796968	test: 0.6623928	best: 0.6620925 (493)	total: 26.6s	remaining: 1m 19s
600:	learn: 0.5633403	test: 0.6636993	best: 0.6619903 (538)	total: 31.9s	remaining: 1m 14s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.66199032
bestIteration = 538

Shrink model to first 539 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.612871           0.614076 0.646797  0.662859     0.235200        0.5 305 219 172 314
validation      catboost  0.593069           0.594395 0.639753  0.661990     0.234977        0.5 293 231 180 306

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\none

================================================================================
exclude_before_2010
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,057; mean weight=1.0000; effective sample size=5057.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6918858	test: 0.6922790	best: 0.6922790 (0)	total: 40.9ms	remaining: 1m 21s
100:	learn: 0.6461248	test: 0.6689714	best: 0.6689134 (98)	total: 5.1s	remaining: 1m 35s
200:	learn: 0.6270499	test: 0.6647187	best: 0.6647187 (200)	total: 10.2s	remaining: 1m 30s
300:	learn: 0.6101210	test: 0.6626118	best: 0.6626118 (300)	total: 15.1s	remaining: 1m 25s
400:	learn: 0.5889246	test: 0.6614168	best: 0.6614168 (400)	total: 20.2s	remaining: 1m 20s
500:	learn: 0.5698290	test: 0.6616320	best: 0.6610493 (451)	total: 25.2s	remaining: 1m 15s
600:	learn: 0.5527423	test: 0.6619940	best: 0.6610493 (451)	total: 30.3s	remaining: 1m 10s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6610492698
bestIteration = 451

Shrink model to first 452 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.607921           0.609006 0.646165  0.662823     0.235191        0.5 304 220 176 310
validation      catboost  0.599010           0.600642 0.646208  0.661049     0.234352        0.5 292 232 173 313

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2010

================================================================================
step_before_2010_025
Temporal weighting:
  mode=step; original train=6,307; effective train=6,307; mean weight=0.8514; effective sample size=5614.6
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920540	test: 0.6921897	best: 0.6921897 (0)	total: 50ms	remaining: 1m 39s
100:	learn: 0.6459641	test: 0.6692986	best: 0.6692648 (99)	total: 5.15s	remaining: 1m 36s
200:	learn: 0.6283978	test: 0.6651940	best: 0.6651085 (198)	total: 10.3s	remaining: 1m 32s
300:	learn: 0.6127482	test: 0.6630539	best: 0.6627615 (286)	total: 15.5s	remaining: 1m 27s
400:	learn: 0.5941752	test: 0.6643491	best: 0.6624118 (319)	total: 20.7s	remaining: 1m 22s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6624117648
bestIteration = 319

Shrink model to first 320 iterations.

Training complete.
Selected model: random_forest
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.605941           0.607023 0.647850  0.662132     0.234873        0.5 303 221 177 309
validation      catboost  0.598020           0.599837 0.642042  0.662412     0.235057        0.5 289 235 171 315

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\step_before_2010_025

================================================================================
exponential_half_life_5
Temporal weighting:
  mode=exponential; original train=6,307; effective train=6,307; mean weight=0.4451; effective sample size=4730.6
Training Random Forest...
Training CatBoost...
0:	learn: 0.6917859	test: 0.6920192	best: 0.6920192 (0)	total: 50.8ms	remaining: 1m 41s
100:	learn: 0.6378530	test: 0.6681157	best: 0.6681157 (100)	total: 5.35s	remaining: 1m 40s
200:	learn: 0.6163439	test: 0.6661041	best: 0.6656041 (184)	total: 10.8s	remaining: 1m 36s
300:	learn: 0.5963048	test: 0.6640670	best: 0.6640670 (300)	total: 16.1s	remaining: 1m 30s
400:	learn: 0.5741473	test: 0.6639445	best: 0.6634957 (368)	total: 21.4s	remaining: 1m 25s
500:	learn: 0.5533296	test: 0.6647674	best: 0.6634957 (368)	total: 26.8s	remaining: 1m 20s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.663495719
bestIteration = 368

Shrink model to first 369 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.600000           0.601224 0.638799  0.664856     0.236203        0.5 298 226 178 308
validation      catboost  0.583168           0.584928 0.638272  0.663496     0.235596        0.5 282 242 179 307

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exponential_half_life_5

In [7]:
rows = []
for strategy, result in results.items():
    for model, metrics in result["validation_metrics"].items():
        rows.append({
            "strategy": strategy,
            "model": model,
            **metrics,
            "effective_train_rows": result["weighting_summary"]["effective_train_rows"],
            "effective_sample_size": result["weighting_summary"]["effective_sample_size"],
            "mean_weight": result["weighting_summary"]["weight_mean"],
        })

comparison = pd.DataFrame(rows).sort_values(
    ["log_loss", "brier_score", "roc_auc"],
    ascending=[True, True, False],
)
comparison

,strategy,model,accuracy,balanced_accuracy,roc_auc,log_loss,brier_score,threshold,tn,fp,fn,tp,effective_train_rows,effective_sample_size,mean_weight
3,exclude_before_2010,catboost,0.599010,0.600642,0.646208,0.661049,0.234352,0.5,292,232,173,313,5057,5057.000000,1.000000
1,none,catboost,0.593069,0.594395,0.639753,0.661990,0.234977,0.5,293,231,180,306,6307,6307.000000,1.000000
4,step_before_2010_025,random_forest,0.605941,0.607023,0.647850,0.662132,0.234873,0.5,303,221,177,309,6307,5614.572235,0.851356
5,step_before_2010_025,catboost,0.598020,0.599837,0.642042,0.662412,0.235057,0.5,289,235,171,315,6307,5614.572235,0.851356
2,exclude_before_2010,random_forest,0.607921,0.609006,0.646165,0.662823,0.235191,0.5,304,220,176,310,5057,5057.000000,1.000000
0,none,random_forest,0.612871,0.614076,0.646797,0.662859,0.235200,0.5,305,219,172,314,6307,6307.000000,1.000000
7,exponential_half_life_5,catboost,0.583168,0.584928,0.638272,0.663496,0.235596,0.5,282,242,179,307,6307,4730.614526,0.445135
6,exponential_half_life_5,random_forest,0.600000,0.601224,0.638799,0.664856,0.236203,0.5,298,226,178,308,6307,4730.614526,0.445135

In [8]:
rf_config = RandomForestConfig()
cat_config = CatBoostConfig()
split_config = SplitConfig()

strategies = {
    "none": TimeWeightConfig(mode="none"),
    "exclude_before_2015": TimeWeightConfig(
        mode="exclude_before", cutoff_date="2015-01-01"
    ),
    "step_before_2015_025": TimeWeightConfig(
        mode="step", cutoff_date="2015-01-01", pre_cutoff_weight=0.25
    ),
    "exponential_half_life_8": TimeWeightConfig(
        mode="exponential", half_life_years=8, minimum_weight=0.10
    ),
}

In [9]:
results = {}
for name, config in strategies.items():
    print("\n" + "=" * 80)
    print(name)
    results[name] = train_time_weighted_experiment(
        project_root=project_root,
        time_weight_config=config,
        rf_config=rf_config,
        cat_config=cat_config,
        split_config=split_config,
        evaluate_test=False,
        experiment_name=name,
    )

================================================================================
none
Temporal weighting:
  mode=none; original train=6,307; effective train=6,307; mean weight=1.0000; effective sample size=6307.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6919777	test: 0.6921598	best: 0.6921598 (0)	total: 48.2ms	remaining: 1m 36s
100:	learn: 0.6436785	test: 0.6693868	best: 0.6693868 (100)	total: 5.65s	remaining: 1m 46s
200:	learn: 0.6269106	test: 0.6643399	best: 0.6643151 (198)	total: 11.1s	remaining: 1m 38s
300:	learn: 0.6131275	test: 0.6635690	best: 0.6632978 (288)	total: 16.5s	remaining: 1m 32s
400:	learn: 0.5961288	test: 0.6627661	best: 0.6627661 (400)	total: 22.1s	remaining: 1m 28s
500:	learn: 0.5796968	test: 0.6623928	best: 0.6620925 (493)	total: 27.6s	remaining: 1m 22s
600:	learn: 0.5633403	test: 0.6636993	best: 0.6619903 (538)	total: 33.1s	remaining: 1m 17s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.66199032
bestIteration = 538

Shrink model to first 539 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.612871           0.614076 0.646797  0.662859     0.235200        0.5 305 219 172 314
validation      catboost  0.593069           0.594395 0.639753  0.661990     0.234977        0.5 293 231 180 306

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\none

================================================================================
exclude_before_2015
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=3,309; mean weight=1.0000; effective sample size=3309.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6916955	test: 0.6921466	best: 0.6921466 (0)	total: 44.8ms	remaining: 1m 29s
100:	learn: 0.6364841	test: 0.6677516	best: 0.6677341 (99)	total: 5.14s	remaining: 1m 36s
200:	learn: 0.6115425	test: 0.6666304	best: 0.6666304 (200)	total: 10.1s	remaining: 1m 30s
300:	learn: 0.5878753	test: 0.6676533	best: 0.6663090 (208)	total: 15.3s	remaining: 1m 26s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6663090161
bestIteration = 208

Shrink model to first 209 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.604950           0.604950 0.629720  0.667439     0.237416        0.5 317 207 192 294
validation      catboost  0.593069           0.594022 0.632598  0.666309     0.236893        0.5 298 226 185 301

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2015

================================================================================
step_before_2015_025
Temporal weighting:
  mode=step; original train=6,307; effective train=6,307; mean weight=0.6435; effective sample size=4711.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920278	test: 0.6921690	best: 0.6921690 (0)	total: 46.7ms	remaining: 1m 33s
100:	learn: 0.6393525	test: 0.6693419	best: 0.6692153 (98)	total: 5.58s	remaining: 1m 45s
200:	learn: 0.6156548	test: 0.6665926	best: 0.6661324 (182)	total: 11.2s	remaining: 1m 40s
300:	learn: 0.5959758	test: 0.6651448	best: 0.6650803 (298)	total: 16.8s	remaining: 1m 34s
400:	learn: 0.5718679	test: 0.6653362	best: 0.6638406 (350)	total: 22.3s	remaining: 1m 28s
500:	learn: 0.5486578	test: 0.6676525	best: 0.6638406 (350)	total: 27.9s	remaining: 1m 23s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6638405597
bestIteration = 350

Shrink model to first 351 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.601980           0.602311 0.638909  0.664350     0.235961        0.5 311 213 189 297
validation      catboost  0.592079           0.594112 0.634848  0.663841     0.235862        0.5 283 241 171 315

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\step_before_2015_025

================================================================================
exponential_half_life_8
Temporal weighting:
  mode=exponential; original train=6,307; effective train=6,307; mean weight=0.5720; effective sample size=5423.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920451	test: 0.6921954	best: 0.6921954 (0)	total: 51.7ms	remaining: 1m 43s
100:	learn: 0.6415100	test: 0.6707290	best: 0.6707290 (100)	total: 5.58s	remaining: 1m 44s
200:	learn: 0.6206601	test: 0.6666595	best: 0.6666286 (198)	total: 11.2s	remaining: 1m 39s
300:	learn: 0.6019573	test: 0.6653417	best: 0.6652487 (236)	total: 16.7s	remaining: 1m 34s
400:	learn: 0.5829832	test: 0.6651599	best: 0.6648124 (324)	total: 22.2s	remaining: 1m 28s
500:	learn: 0.5652196	test: 0.6650273	best: 0.6644757 (453)	total: 27.9s	remaining: 1m 23s
600:	learn: 0.5481201	test: 0.6661924	best: 0.6644757 (453)	total: 33.5s	remaining: 1m 18s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6644756929
bestIteration = 453

Shrink model to first 454 iterations.

Training complete.
Selected model: random_forest
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest   0.60495           0.605622 0.641418  0.663668     0.235625        0.5 308 216 183 303
validation      catboost   0.60099           0.602775 0.635276  0.664476     0.236062        0.5 291 233 170 316

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exponential_half_life_8

In [10]:
rows = []
for strategy, result in results.items():
    for model, metrics in result["validation_metrics"].items():
        rows.append({
            "strategy": strategy,
            "model": model,
            **metrics,
            "effective_train_rows": result["weighting_summary"]["effective_train_rows"],
            "effective_sample_size": result["weighting_summary"]["effective_sample_size"],
            "mean_weight": result["weighting_summary"]["weight_mean"],
        })

comparison = pd.DataFrame(rows).sort_values(
    ["log_loss", "brier_score", "roc_auc"],
    ascending=[True, True, False],
)
comparison

,strategy,model,accuracy,balanced_accuracy,roc_auc,log_loss,brier_score,threshold,tn,fp,fn,tp,effective_train_rows,effective_sample_size,mean_weight
1,none,catboost,0.593069,0.594395,0.639753,0.661990,0.234977,0.5,293,231,180,306,6307,6307.000000,1.000000
0,none,random_forest,0.612871,0.614076,0.646797,0.662859,0.235200,0.5,305,219,172,314,6307,6307.000000,1.000000
6,exponential_half_life_8,random_forest,0.604950,0.605622,0.641418,0.663668,0.235625,0.5,308,216,183,303,6307,5423.037173,0.571970
5,step_before_2015_025,catboost,0.592079,0.594112,0.634848,0.663841,0.235862,0.5,283,241,171,315,6307,4710.999893,0.643491
4,step_before_2015_025,random_forest,0.601980,0.602311,0.638909,0.664350,0.235961,0.5,311,213,189,297,6307,4710.999893,0.643491
7,exponential_half_life_8,catboost,0.600990,0.602775,0.635276,0.664476,0.236062,0.5,291,233,170,316,6307,5423.037173,0.571970
3,exclude_before_2015,catboost,0.593069,0.594022,0.632598,0.666309,0.236893,0.5,298,226,185,301,3309,3309.000000,1.000000
2,exclude_before_2015,random_forest,0.604950,0.604950,0.629720,0.667439,0.237416,0.5,317,207,192,294,3309,3309.000000,1.000000

## 3. Initial Findings

CatBoost improves slightly when a limited amount of older data is removed, but performance worsens with the 2015 cutoff. Exponential decay provides no benefit, while step weighting is nearly equivalent to a hard cutoff. Random Forest does not improve under these weighting strategies.

## 4. Refined Cutoff Search

Several cutoff years between 2000 and 2010 are compared to determine whether a stable boundary exists.

In [11]:
rf_config = RandomForestConfig()
cat_config = CatBoostConfig()
split_config = SplitConfig()

strategies = {
    "none": TimeWeightConfig(mode="none"),
    "exclude_before_2000": TimeWeightConfig(
        mode="exclude_before", cutoff_date="2000-01-01"
    ),
    "exclude_before_2002": TimeWeightConfig(
            mode="exclude_before", cutoff_date="2002-01-01"
    ),
    "exclude_before_2004": TimeWeightConfig(
            mode="exclude_before", cutoff_date="2004-01-01"
    ),
    "exclude_before_2006": TimeWeightConfig(
            mode="exclude_before", cutoff_date="2006-01-01"
    ),
    "exclude_before_2008": TimeWeightConfig(
            mode="exclude_before", cutoff_date="2008-01-01"
    ),
    "exclude_before_2010": TimeWeightConfig(
            mode="exclude_before", cutoff_date="2010-01-01"
    ),
}

In [12]:
results = {}
for name, config in strategies.items():
    print("\n" + "=" * 80)
    print(name)
    results[name] = train_time_weighted_experiment(
        project_root=project_root,
        time_weight_config=config,
        rf_config=rf_config,
        cat_config=cat_config,
        split_config=split_config,
        evaluate_test=False,
        experiment_name=name,
    )

================================================================================
none
Temporal weighting:
  mode=none; original train=6,307; effective train=6,307; mean weight=1.0000; effective sample size=6307.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6919777	test: 0.6921598	best: 0.6921598 (0)	total: 44.7ms	remaining: 1m 29s
100:	learn: 0.6436785	test: 0.6693868	best: 0.6693868 (100)	total: 5.69s	remaining: 1m 47s
200:	learn: 0.6269106	test: 0.6643399	best: 0.6643151 (198)	total: 11.3s	remaining: 1m 41s
300:	learn: 0.6131275	test: 0.6635690	best: 0.6632978 (288)	total: 16.8s	remaining: 1m 34s
400:	learn: 0.5961288	test: 0.6627661	best: 0.6627661 (400)	total: 22.4s	remaining: 1m 29s
500:	learn: 0.5796968	test: 0.6623928	best: 0.6620925 (493)	total: 27.8s	remaining: 1m 23s
600:	learn: 0.5633403	test: 0.6636993	best: 0.6619903 (538)	total: 33.3s	remaining: 1m 17s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.66199032
bestIteration = 538

Shrink model to first 539 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.612871           0.614076 0.646797  0.662859     0.235200        0.5 305 219 172 314
validation      catboost  0.593069           0.594395 0.639753  0.661990     0.234977        0.5 293 231 180 306

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\none

================================================================================
exclude_before_2000
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=6,088; mean weight=1.0000; effective sample size=6088.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920808	test: 0.6925042	best: 0.6925042 (0)	total: 50.7ms	remaining: 1m 41s
100:	learn: 0.6441379	test: 0.6679297	best: 0.6679297 (100)	total: 5.63s	remaining: 1m 45s
200:	learn: 0.6271877	test: 0.6633161	best: 0.6633161 (200)	total: 11.2s	remaining: 1m 39s
300:	learn: 0.6128379	test: 0.6612412	best: 0.6612412 (300)	total: 16.8s	remaining: 1m 34s
400:	learn: 0.5947364	test: 0.6612110	best: 0.6612076 (389)	total: 22.3s	remaining: 1m 29s
500:	learn: 0.5779429	test: 0.6607038	best: 0.6605680 (411)	total: 27.9s	remaining: 1m 23s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6605680427
bestIteration = 411

Shrink model to first 412 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.606931           0.607828 0.644414  0.663543     0.235542        0.5 306 218 179 307
validation      catboost  0.602970           0.604385 0.644645  0.660568     0.234221        0.5 297 227 174 312

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2000

================================================================================
exclude_before_2002
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=6,007; mean weight=1.0000; effective sample size=6007.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6916918	test: 0.6923643	best: 0.6923643 (0)	total: 54ms	remaining: 1m 47s
100:	learn: 0.6434759	test: 0.6682434	best: 0.6682390 (99)	total: 5.51s	remaining: 1m 43s
200:	learn: 0.6257756	test: 0.6637673	best: 0.6637673 (200)	total: 11.1s	remaining: 1m 39s
300:	learn: 0.6112066	test: 0.6625112	best: 0.6622113 (284)	total: 16.8s	remaining: 1m 34s
400:	learn: 0.5930278	test: 0.6623736	best: 0.6620742 (361)	total: 22.4s	remaining: 1m 29s
500:	learn: 0.5753336	test: 0.6633788	best: 0.6620300 (420)	total: 28.1s	remaining: 1m 23s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.662029994
bestIteration = 420

Shrink model to first 421 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.600990           0.601879 0.640255  0.664575     0.236066        0.5 303 221 182 304
validation      catboost  0.593069           0.594395 0.642941  0.662030     0.234832        0.5 293 231 180 306

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2002

================================================================================
exclude_before_2004
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,916; mean weight=1.0000; effective sample size=5916.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6916251	test: 0.6924003	best: 0.6924003 (0)	total: 54.5ms	remaining: 1m 49s
100:	learn: 0.6410454	test: 0.6695014	best: 0.6695014 (100)	total: 5.6s	remaining: 1m 45s
200:	learn: 0.6240036	test: 0.6646012	best: 0.6646012 (200)	total: 11s	remaining: 1m 38s
300:	learn: 0.6090428	test: 0.6632468	best: 0.6631441 (254)	total: 16.5s	remaining: 1m 32s
400:	learn: 0.5910049	test: 0.6632833	best: 0.6628180 (330)	total: 21.9s	remaining: 1m 27s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6628180084
bestIteration = 330

Shrink model to first 331 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.612871           0.613703 0.642745  0.664093     0.235806        0.5 310 214 177 309
validation      catboost  0.600000           0.600925 0.640000  0.662818     0.235239        0.5 302 222 182 304

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2004

================================================================================
exclude_before_2006
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,798; mean weight=1.0000; effective sample size=5798.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6920454	test: 0.6922470	best: 0.6922470 (0)	total: 48.5ms	remaining: 1m 36s
100:	learn: 0.6436776	test: 0.6697066	best: 0.6697066 (100)	total: 5.32s	remaining: 1m 40s
200:	learn: 0.6255816	test: 0.6646973	best: 0.6646973 (200)	total: 10.4s	remaining: 1m 33s
300:	learn: 0.6110813	test: 0.6624294	best: 0.6621890 (297)	total: 15.6s	remaining: 1m 28s
400:	learn: 0.5921271	test: 0.6621590	best: 0.6618853 (325)	total: 21s	remaining: 1m 23s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6618853361
bestIteration = 325

Shrink model to first 326 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest   0.60099           0.601805 0.643275  0.663400     0.235509        0.5 304 220 183 303
validation      catboost   0.60297           0.604758 0.641371  0.661885     0.234841        0.5 292 232 169 317

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2006

================================================================================
exclude_before_2008
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,471; mean weight=1.0000; effective sample size=5471.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6914889	test: 0.6924723	best: 0.6924723 (0)	total: 46.3ms	remaining: 1m 32s
100:	learn: 0.6449570	test: 0.6688084	best: 0.6688084 (100)	total: 5.26s	remaining: 1m 38s
200:	learn: 0.6267349	test: 0.6656756	best: 0.6656473 (198)	total: 10.6s	remaining: 1m 34s
300:	learn: 0.6102402	test: 0.6646591	best: 0.6644176 (229)	total: 15.9s	remaining: 1m 29s
400:	learn: 0.5905273	test: 0.6626452	best: 0.6626452 (400)	total: 21.4s	remaining: 1m 25s
500:	learn: 0.5710815	test: 0.6631700	best: 0.6623683 (419)	total: 26.7s	remaining: 1m 19s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6623682878
bestIteration = 419

Shrink model to first 420 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.605941           0.606725 0.646526  0.662513     0.235057        0.5 307 217 181 305
validation      catboost  0.603960           0.605488 0.638763  0.662368     0.235127        0.5 296 228 172 314

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2008

================================================================================
exclude_before_2010
Temporal weighting:
  mode=exclude_before; original train=6,307; effective train=5,057; mean weight=1.0000; effective sample size=5057.0
Training Random Forest...
Training CatBoost...
0:	learn: 0.6918858	test: 0.6922790	best: 0.6922790 (0)	total: 50.1ms	remaining: 1m 40s
100:	learn: 0.6461248	test: 0.6689714	best: 0.6689134 (98)	total: 5.36s	remaining: 1m 40s
200:	learn: 0.6270499	test: 0.6647187	best: 0.6647187 (200)	total: 10.7s	remaining: 1m 35s
300:	learn: 0.6101210	test: 0.6626118	best: 0.6626118 (300)	total: 16.1s	remaining: 1m 31s
400:	learn: 0.5889246	test: 0.6614168	best: 0.6614168 (400)	total: 21.9s	remaining: 1m 27s
500:	learn: 0.5698290	test: 0.6616320	best: 0.6610493 (451)	total: 27.3s	remaining: 1m 21s
600:	learn: 0.5527423	test: 0.6619940	best: 0.6610493 (451)	total: 32.8s	remaining: 1m 16s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.6610492698
bestIteration = 451

Shrink model to first 452 iterations.

Training complete.
Selected model: catboost
     split         model  accuracy  balanced_accuracy  roc_auc  log_loss  brier_score  threshold  tn  fp  fn  tp
validation random_forest  0.607921           0.609006 0.646165  0.662823     0.235191        0.5 304 220 176 310
validation      catboost  0.599010           0.600642 0.646208  0.661049     0.234352        0.5 292 232 173 313

Artifacts: C:\Users\pablo\Desktop\PABLO\PROGRAMACION\UFC_PREDICTOR\artifacts\modeling\experiments\exclude_before_2010

In [13]:
rows = []
for strategy, result in results.items():
    for model, metrics in result["validation_metrics"].items():
        rows.append({
            "strategy": strategy,
            "model": model,
            **metrics,
            "effective_train_rows": result["weighting_summary"]["effective_train_rows"],
            "effective_sample_size": result["weighting_summary"]["effective_sample_size"],
            "mean_weight": result["weighting_summary"]["weight_mean"],
        })

comparison = pd.DataFrame(rows).sort_values(
    ["log_loss", "brier_score", "roc_auc"],
    ascending=[True, True, False],
)
comparison

,strategy,model,accuracy,balanced_accuracy,roc_auc,log_loss,brier_score,threshold,tn,fp,fn,tp,effective_train_rows,effective_sample_size,mean_weight
3,exclude_before_2000,catboost,0.602970,0.604385,0.644645,0.660568,0.234221,0.5,297,227,174,312,6088,6088.0,1.0
13,exclude_before_2010,catboost,0.599010,0.600642,0.646208,0.661049,0.234352,0.5,292,232,173,313,5057,5057.0,1.0
9,exclude_before_2006,catboost,0.602970,0.604758,0.641371,0.661885,0.234841,0.5,292,232,169,317,5798,5798.0,1.0
1,none,catboost,0.593069,0.594395,0.639753,0.661990,0.234977,0.5,293,231,180,306,6307,6307.0,1.0
5,exclude_before_2002,catboost,0.593069,0.594395,0.642941,0.662030,0.234832,0.5,293,231,180,306,6007,6007.0,1.0
11,exclude_before_2008,catboost,0.603960,0.605488,0.638763,0.662368,0.235127,0.5,296,228,172,314,5471,5471.0,1.0
10,exclude_before_2008,random_forest,0.605941,0.606725,0.646526,0.662513,0.235057,0.5,307,217,181,305,5471,5471.0,1.0
7,exclude_before_2004,catboost,0.600000,0.600925,0.640000,0.662818,0.235239,0.5,302,222,182,304,5916,5916.0,1.0
12,exclude_before_2010,random_forest,0.607921,0.609006,0.646165,0.662823,0.235191,0.5,304,220,176,310,5057,5057.0,1.0
0,none,random_forest,0.612871,0.614076,0.646797,0.662859,0.235200,0.5,305,219,172,314,6307,6307.0,1.0
8,exclude_before_2006,random_forest,0.600990,0.601805,0.643275,0.663400,0.235509,0.5,304,220,183,303,5798,5798.0,1.0
2,exclude_before_2000,random_forest,0.606931,0.607828,0.644414,0.663543,0.235542,0.5,306,218,179,307,6088,6088.0,1.0
6,exclude_before_2004,random_forest,0.612871,0.613703,0.642745,0.664093,0.235806,0.5,310,214,177,309,5916,5916.0,1.0
4,exclude_before_2002,random_forest,0.600990,0.601879,0.640255,0.664575,0.236066,0.5,303,221,182,304,6007,6007.0,1.0

## Summary

Progressive weighting was discarded. Removing some early fights produced a small CatBoost improvement, but no cutoff was consistent enough to include in the final training strategy.